# -*- coding: utf-8 -*-
"""Copy of Welcome To Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uG68ZFQUz3PyLgWV91EY9kvi3BWM_LfK
"""

install.packages("ordinal")

library(ordinal)

my_data <- read.csv("/processed_file.csv")

data <- read.csv("/processed_file.csv")

my_data$response <- factor(my_data$response)

View(my_data)

irony_model1 <- clmm(as.factor(ironic) ~ age_range + (1 | response), data = my_data)

summary(irony_model1)

irony_model2 <- clmm(as.factor(nonironic) ~ age_range + (1 | response), data = my_data)

summary(irony_model2)

irony_model3 <- clmm(as.factor(rude) ~ age_range + (1 | response), data = my_data)

summary(irony_model3)

irony_model4 <- clmm(as.factor(polite) ~ age_range + (1 | response), data = my_data)

summary(irony_model4)

irony_model5 <- clmm(as.factor(ironic) ~ gender + (1 | response), data = my_data)

summary(irony_model5)

irony_model6 <- clmm(as.factor(nonironic) ~ gender + (1 | response), data = my_data)

summary(irony_model6)

irony_model7 <- clmm(as.factor(rude) ~ gender + (1 | response), data = my_data)

summary(irony_model7)

irony_model8 <- clmm(as.factor(polite) ~ gender + (1 | response), data = my_data)

summary(irony_model8)

power_d1 <- clmm(as.factor(ironic) ~ sup.inf + (1 | response), data = my_data)

summary(power_d1)

power_d2 <- clmm(as.factor(nonironic) ~ sup.inf + (1 | response), data = my_data)

summary(power_d2)

power_d3 <- clmm(as.factor(rude) ~ sup.inf + (1 | response), data = my_data)

summary(power_d3)

power_d4 <- clmm(as.factor(polite) ~ sup.inf + (1 | response), data = my_data)

summary(power_d4)

power_d5 <- clmm(as.factor(ironic) ~ inf.sup + (1 | response), data = my_data)

summary(power_d5)

power_d6 <- clmm(as.factor(nonironic) ~ inf.sup + (1 | response), data = my_data)

summary(power_d6)

power_d7 <- clmm(as.factor(rude) ~ inf.sup + (1 | response), data = my_data)

summary(power_d7)

power_d8 <- clmm(as.factor(polite) ~ inf.sup + (1 | response), data = my_data)

summary(power_d8)

power_d9 <- clmm(as.factor(ironic) ~ equal + (1 | response), data = my_data)

summary(power_d9)

power_d10 <- clmm(as.factor(nonironic) ~ equal + (1 | response), data = my_data)

summary(power_d10)

power_d11 <- clmm(as.factor(rude) ~ equal + (1 | response), data = my_data)

summary(power_d11)

power_d12 <- clmm(as.factor(polite) ~ equal + (1 | response), data = my_data)

summary(power_d12)